server:
  port: 8888

spring:
  # mariadb 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${db.local.url}
    username: ${db.local.username}
    password: ${db.local.password}
    
  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

    defer-datasource-initialization: true
  # sql 자동 생성
  sql:
    init:
      mode: always

logging:
  level:

    dev.memory: debug

    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true