

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: ${db.local.url}
    username: ${db.local.username}
    password: ${db.local.password}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    dev.memory: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

queue:
  activation:
    batch-size: 10           # 한 번에 활성화할 사용자 수
    max-active-users: 100    # 스케줄당 최대 활성 사용자 수

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      tracing:
        include-parameter-values: true
server:
  port: 8888